# Generated by Django 4.1.3 on 2022-11-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.FileField(upload_to='images/category'),
        ),
    ]
