# Generated by Django 4.1.3 on 2022-12-02 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0004_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bidtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
