# Generated by Django 4.1.3 on 2022-12-02 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0005_bids_bidtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientjobs',
            name='jobtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
