# Generated by Django 3.2.8 on 2022-12-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0006_clientjobs_jobtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bidaccepted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='clientjobs',
            name='bidder',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
