# Generated by Django 4.1.3 on 2022-12-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0007_auto_20221209_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientjobs',
            name='reported',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
