# Generated by Django 4.1.3 on 2022-12-09 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0009_jobreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobreport',
            old_name='user',
            new_name='reportuser',
        ),
    ]
