# Generated by Django 3.2.8 on 2022-12-15 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientside', '0010_rename_user_jobreport_reportuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientjobs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientjob', to=settings.AUTH_USER_MODEL),
        ),
    ]
