# Generated by Django 4.1.4 on 2022-12-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0011_alter_clientjobs_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientjobs',
            name='expiry_on',
            field=models.DateTimeField(null=True),
        ),
    ]
