# Generated by Django 4.1.3 on 2022-11-25 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='educations',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.education'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experiences',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.experience'),
            preserve_default=False,
        ),
    ]
