# Generated by Django 4.1.3 on 2022-11-25 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_education_user_remove_experience_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='educations',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='experiences',
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
