# Generated by Django 4.1.3 on 2022-11-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userprofile_educations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_freelancer',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
