# Generated by Django 4.1.4 on 2022-12-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_newuser_is_freelancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='active_membership',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='membership_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
