# Generated by Django 4.1.4 on 2022-12-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_newuser_active_membership_newuser_membership_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='images/user/4.png', null=True, upload_to='images/user'),
        ),
    ]
