# Generated by Django 4.1.4 on 2022-12-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_userprofile_about_alter_userprofile_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='profile_photo',
            field=models.ImageField(blank=True, default='images/user/4.png', null=True, upload_to='images/user'),
        ),
    ]
