# Generated by Django 4.1.4 on 2022-12-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_newuser_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='email_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='otp',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
