# Generated by Django 4.1.4 on 2022-12-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_newuser_email_token_newuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
