export const CATEGORY_REQUEST = 'CATEGORY_REQUEST'
export const CATEGORY_SUCCESS = 'CATEGORY_SUCCESS'
export const CATEGORY_FAIL = 'CATEGORY_FAIL'


export const JOBPOST_REQUEST = 'JOBPOST_REQUEST'
export const JOBPOST_SUCCESS = 'JOBPOST_SUCCESS'
export const JOBPOST_FAIL = 'JOBPOST_FAIL'


export const SINGLEJOBPOST_REQUEST = 'SINGLEJOBPOST_REQUEST'
export const SINGLEJOBPOST_SUCCESS = 'SINGLEJOBPOST_SUCCESS'
export const SINGLEJOBPOST_FAIL = 'SINGLEJOBPOST_FAIL'