export const CATEGORY_REQUEST = "CATEGORY_REQUEST";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const CATEGORY_FAIL = "CATEGORY_FAIL";

export const JOBPOST_REQUEST = "JOBPOST_REQUEST";
export const JOBPOST_SUCCESS = "JOBPOST_SUCCESS";
export const JOBPOST_FAIL = "JOBPOST_FAIL";

export const SINGLEJOBPOST_REQUEST = "SINGLEJOBPOST_REQUEST";
export const SINGLEJOBPOST_SUCCESS = "SINGLEJOBPOST_SUCCESS";
export const SINGLEJOBPOST_FAIL = "SINGLEJOBPOST_FAIL";

export const SERVICEPOST_REQUEST = "SERVICEPOST_REQUEST";
export const SERVICEPOST_SUCCESS = "SERVICEPOST_SUCCESS";
export const SERVICEPOST_FAIL = "SERVICEPOST_FAIL";

export const SINGLESERVICEPOST_REQUEST = "SINGLESERVICEPOST_REQUEST";
export const SINGLESERVICEPOST_SUCCESS = "SINGLESERVICEPOST_SUCCESS";
export const SINGLESERVICEPOST_FAIL = "SINGLESERVICEPOST_FAIL";

export const USERPROFILE_REQUEST = "USERPROFILE_REQUEST";
export const USERPROFILE_SUCCESS = "USERPROFILE_SUCCESS";
export const USERPROFILE_FAIL = "USERPROFILE_FAIL";

export const ALLUSERS_REQUEST = "ALLUSERS_REQUEST";
export const ALLUSERS_SUCCESS = "ALLUSERS_SUCCESS";
export const ALLUSERS_FAIL = "ALLUSERS_FAIL";

export const SINGLEUSERS_REQUEST = "SINGLEUSERS_REQUEST";
export const SINGLEUSERS_SUCCESS = "SINGLEUSERS_SUCCESS";
export const SINGLEUSERS_FAIL = "SINGLEUSERS_FAIL";

export const JOB_PURCHASE_HISTORY_REQUEST = "JOB_PURCHASE_HISTORY_REQUEST";
export const JOB_PURCHASE_HISTORY_SUCCESS = "JOB_PURCHASE_HISTORY_SUCCESS";
export const JOB_PURCHASE_HISTORY_FAIL = "JOB_PURCHASE_HISTORY_FAIL";

export const SERVICE_PURCHASE_HISTORY_REQUEST = "SERVICE_PURCHASE_HISTORY_REQUEST";
export const SERVICE_PURCHASE_HISTORY_SUCCESS = "SERVICE_PURCHASE_HISTORY_SUCCESS";
export const SERVICE_PURCHASE_HISTORY_FAIL = "SERVICE_PURCHASE_HISTORY_FAIL";

export const FREELANCER_REQUEST_REQUEST = "FREELANCER_REQUEST_REQUEST";
export const FREELANCER_REQUEST_SUCCESS = "FREELANCER_REQUEST_SUCCESS";
export const FREELANCER_REQUEST_FAIL = "FREELANCER_REQUEST_FAIL";
