# Generated by Django 4.1.3 on 2022-12-01 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0003_clientjobs'),
        ('freelancerside', '0002_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='clientjob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_job', to='clientside.clientjobs'),
        ),
    ]
