# Generated by Django 4.1.3 on 2022-12-02 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancerside', '0003_alter_bids_clientjob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='daysrequrired',
            new_name='daysrequired',
        ),
    ]
