# Generated by Django 3.2.8 on 2022-12-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancerside', '0007_servicerating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerating',
            old_name='user',
            new_name='reviewuser',
        ),
    ]
