# Generated by Django 4.1.3 on 2022-12-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancerside', '0009_servicerating_reviewtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerservice',
            name='reported',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
