# Generated by Django 4.1.4 on 2022-12-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancerside', '0014_freelancerservice_expiry_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerservice',
            name='expired',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
