# Generated by Django 4.1.4 on 2023-01-05 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freelancerside', '0019_alter_freelancerservice_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerservice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='getservice', to=settings.AUTH_USER_MODEL),
        ),
    ]
