# Generated by Django 4.1.4 on 2023-01-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancerside', '0020_alter_freelancerservice_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyservice',
            old_name='serviceid',
            new_name='getservice',
        ),
    ]
